In [3]:
import numpy as np

In [4]:
my_list = [1, 2, 3, 4, 5]

In [5]:
np_array = np.array(my_list)
print(np_array)

[1 2 3 4 5]


In [6]:
zeros_array = np.zeros((2, 3))  # 2x3 boyutunda
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones_array = np.ones((3, 2))  # 3x2 boyutunda
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
linspace_array = np.linspace(0, 5, 10)  # 0 ile 5 arasında
print(linspace_array)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [9]:
my_array = np.array([1, 2, 3, 4, 5])

In [10]:
print(my_array.ndim)

1


In [11]:
print(my_array.shape)


(5,)


In [12]:
print(my_array.dtype)

int32


In [13]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [14]:
print(array1 + array2)


[5 7 9]


In [15]:
print(array1 - array2)


[-3 -3 -3]


In [16]:
print(array1 * array2)


[ 4 10 18]


In [17]:
print(array1 / array2)


[0.25 0.4  0.5 ]


In [18]:
print(np.dot(array1, array2))


32


In [19]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
print(my_array[:, 1])

[2 5 8]


In [21]:
print(my_array[:2, 1:])

[[2 3]
 [5 6]]


In [22]:
print(my_array[0, 0])

1


In [23]:
print(my_array[1])

[4 5 6]
