In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential ([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

C:\Users\alpnn\AppData\Local\anaconda3\envs\YoloV8\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
pred = model(x_train[:1]).numpy()
pred

array([[ 0.11919825, -0.25618288,  0.1212427 , -0.26537016, -0.06665593,
         0.06997078,  0.1453432 , -0.17681132, -0.2996612 , -0.17578514]],
      dtype=float32)

In [6]:
tf.nn.softmax(pred).numpy()

array([[0.12012318, 0.08252792, 0.12036902, 0.08177318, 0.09974965,
        0.11435301, 0.12330521, 0.08934526, 0.07901663, 0.08943699]],
      dtype=float32)

In [7]:
loss_ = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [8]:
loss_(y_train[:1], pred).numpy()

2.1684651

In [9]:
model.compile(optimizer = 'adam',
             loss = loss_,
             metrics = ['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8604 - loss: 0.4775
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9549 - loss: 0.1490
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9686 - loss: 0.1057
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9735 - loss: 0.0863
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9754 - loss: 0.0763


In [12]:
model.evaluate(x_test, y_test, verbose = 2)

313/313 - 0s - 1ms/step - accuracy: 0.9770 - loss: 0.0771


[0.07705109566450119, 0.9769999980926514]

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.0058799e-09, 5.7234826e-07, 2.3852374e-06, 1.0982665e-03,
        5.1534417e-09, 3.6531844e-07, 2.3086926e-11, 9.9889612e-01,
        9.7536395e-07, 1.2746307e-06],
       [1.2867098e-08, 2.0224063e-05, 9.9996388e-01, 7.6834904e-06,
        8.9732714e-15, 5.9160720e-06, 8.9384500e-09, 5.6283526e-13,
        2.2497125e-06, 1.0119379e-12],
       [7.0453865e-08, 9.9895704e-01, 1.5265751e-04, 1.2954236e-05,
        1.2285428e-05, 2.7008837e-05, 7.3234664e-06, 5.8194279e-04,
        2.4830943e-04, 3.4816898e-07],
       [9.9988842e-01, 3.5205245e-09, 1.0919565e-05, 7.2871387e-07,
        8.3835459e-08, 2.4096239e-06, 8.8498149e-05, 8.6787122e-06,
        7.4755730e-09, 1.6048519e-07],
       [4.5985578e-07, 8.7022851e-09, 6.7114815e-06, 1.1372099e-06,
        9.9694234e-01, 4.5718926e-07, 7.4684681e-07, 4.4179178e-05,
        1.9996953e-06, 3.0018885e-03]], dtype=float32)>