In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad = True)
print(x)

tensor([ 2.3472, -1.5444, -0.1906], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([4.3472, 0.4556, 1.8094], grad_fn=<AddBackward0>)


In [6]:
z = y * y * 2
z = z.mean()
print(z)

tensor(14.9196, grad_fn=<MeanBackward0>)


In [7]:
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)
z.backward()
print(x.grad)

tensor([5.7962, 0.6075, 2.4125])


In [8]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
  model_cikis = (weights * 3).sum()
  model_cikis.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [11]:

optimizer = torch.optim.SGD(weights, lr = 0.01)

optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [10]:
z.backward()
weights.grad.zero_()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.