In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar.ndim

0

In [6]:
scalar.item

<function Tensor.item>

In [7]:
vector = torch.tensor([7,7])

In [8]:
vector.ndim

1

In [12]:
vector.size()

torch.Size([2])

In [14]:
matrix = torch.tensor([[7,8],[9,10]])

print(matrix.ndim)
print(matrix[0])
print(matrix.shape)

2
tensor([7, 8])
torch.Size([2, 2])


In [15]:
tensor = torch.tensor([[[1,2,3],[3,6,9],[5,10,15]]])
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

3
torch.Size([1, 3, 3])
tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [ 5, 10, 15]])


In [17]:
random_tensor = torch.rand(3,4)
print(random_tensor.ndim)

2


In [21]:
ones = torch.ones(size = (3, 4))
print(ones.dtype)

torch.float32


In [23]:
one_to_ten = torch.arange(start=1, end=11, step=1)

ten_zeros = torch.zeros_like(input=one_to_ten)

In [22]:
float_16 = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
print(float_16.dtype)

torch.float16


In [25]:
float_16 = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16, device = 'cuda', requires_grad = False)

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)

float_16_tensor = float_32_tensor.type(torch.float16)

In [28]:
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [29]:
tensor = torch.tensor([1, 2, 3])

result_add = torch.add(tensor, 10)
print(result_add)

result_sub = torch.sub(tensor, 10)
print(result_sub)

result_mul = torch.mul(tensor, 10)
print(result_mul)

result_div = torch.div(tensor, 10)
print(result_div)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [30]:
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)

tensor(14)

In [32]:
tensor = torch.tensor([[1, 2, 3], [1, 2, 3]])
print(tensor.shape)
print(tensor.T)
print(tensor.T.shape)

torch.Size([2, 3])
tensor([[1, 1],
        [2, 2],
        [3, 3]])
torch.Size([3, 2])


In [33]:
tensor = torch.tensor([[1, 2, 3], [1, 2, 3]])

print(torch.min(tensor))
print(torch.max(tensor))
print(torch.mean(tensor.float()))
print(torch.sum(tensor))

tensor(1)
tensor(3)
tensor(2.)
tensor(12)
